/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

// OneSignal is loaded into the worker generated by next-pwa. There must be a
// single worker for scope "/"; a second worker would replace offline support.
self.importScripts('https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js');
